default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog
  username: blog
  password: blog
  host: localhost

test:
  <<: *default
  database: blog_test
  username: blog
  password: blog
  host: localhost

production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV['RAILS-REST-API_DATABASE_PASSWORD'] %>
